version: '3'
services:

  # Home Assistant
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - ./homeassistant/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
    network_mode: host
    restart: unless-stopped
    privileged: true
    # networks:
    #   - iapalandi-network


  # Mosquitto MQTT
  # user: !secret mosquitto_user
  # pwd: !secret mosquitto_pwd
  # $ docker exec mosquitto mosquitto_passwd -b /mosquitto/config/password.txt admin mosquitto
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    depends_on:
      - homeassistant
    # networks:
    #   - iapalandi-network


  # Node Red
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    depends_on:
      - homeassistant
    # networks:
    #   - iapalandi-network
