# Rabbitmq em cluster
version: '3'
services:
  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    # command: rabbitmq-server
    hostname: rabbitmq1
    ports:
      - "8080:15672"   # HTTP management UI, localhost:8080
    network_mode: "bridge"
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=iapalandi_secret_phrase
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=pwdadmin
     - CLUSTERED=true  # Definir que rodaremos em modo cluster

  rabbitmq2:
    image: rabbitmq:3-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    ports:
      - "8081:15672"   # HTTP management UI, localhost:8081
    network_mode: "bridge"
    volumes:
      - $PWD/storage/rabbitmq2:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=iapalandi_secret_phrase
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=pwdadmin
     - CLUSTERED=true  # Definir que rodaremos em modo cluster
    links:
     - rabbitmq1:rabbitmq1
   
  rabbitmq3:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    ports:
      - "8082:15672"
    network_mode: "bridge"
    volumes:
      - $PWD/storage/rabbitmq3:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=iapalandi_secret_phrase
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=pwdadmin
     - CLUSTERED=true
    links:
     - rabbitmq1:rabbitmq1
     - rabbitmq2:rabbitmq2

  rabbitmq4:
    image: rabbitmq:3-management
    container_name: rabbitmq4
    hostname: rabbitmq4
    ports:
      - "8083:15672"
    network_mode: "bridge"
    volumes:
      - $PWD/storage/rabbitmq4:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=iapalandi_secret_phrase
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=pwdadmin
     - CLUSTERED=true
    links:
     - rabbitmq1:rabbitmq1
     - rabbitmq2:rabbitmq2
     - rabbitmq3:rabbitmq3

  haproxy:
    image: haproxy:2.2
    container_name: haproxy
    hostname: haproxy
    ports:
      - 5672:5672      # AMQP protocol port
      - 20000:20000
    network_mode: "bridge"
    links:
      - rabbitmq1:rabbitmq1
      - rabbitmq2:rabbitmq2
      - rabbitmq3:rabbitmq3
      - rabbitmq4:rabbitmq4